apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cluster/rook-ceph-cluster/
  - service-monitor.yaml
  - exporter-service-monitor.yaml
  - prometheus.yaml
  - prometheus-service.yaml
helmCharts:
  - name: rook-ceph-cluster
    repo: https://charts.rook.io/release
    version: 1.19.2
    releaseName: rook-ceph-cluster
    namespace: rook-ceph
    includeCRDs: true
    valuesFile: ../../../../../helm/overlays/scots-lab/cluster/rook-ceph-cluster/values-scots-lab.yaml
patches:
  - patch: |-
      apiVersion: snapshot.storage.k8s.io/v1
      kind: VolumeSnapshotClass
      metadata:
        name: ceph-block
        labels:
          velero.io/csi-volumesnapshot-class: "true"
  - patch: |-
      apiVersion: snapshot.storage.k8s.io/v1
      kind: VolumeSnapshotClass
      metadata:
        name: ceph-filesystem
        labels:
          velero.io/csi-volumesnapshot-class: "true"
# Trigger CI rebuild