apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/apps/uptime-kuma/
helmCharts:
  - name: uptime-kuma
    repo: https://helm.irsigler.cloud
    releaseName: uptime-kuma
    namespace: uptime-kuma
    version: 4.0.0
    includeCRDs: false
    valuesFile: ../../../../../helm/overlays/scots-lab/apps/uptime-kuma/values-scots-lab.yaml
