# Rook Ceph Cluster values for monitoring
cephImage:
  tag: v20.2.0
  allowUnsupported: true

monitoring:
  enabled: true
  createPrometheusRules: true
  # metricsDisabled is false by default when enabled is true

cephClusterSpec:
  skipUpgradeChecks: true
  network:
    provider: host
  dashboard:
    ssl: false
    port: 7000
  annotations:
    dashboard:
      omni-kube-service-exposer.sidero.dev/port: "7000"
      omni-kube-service-exposer.sidero.dev/label: "Ceph Dashboard"
      omni-kube-service-exposer.sidero.dev/prefix: "cephdash"
