apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umami-postgres-data
  namespace: umami
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
