apiVersion: v1
kind: Service
metadata:
  name: umami
  namespace: umami
  annotations:
    omni-kube-service-exposer.sidero.dev/port: "50087"
    omni-kube-service-exposer.sidero.dev/label: "Umami Analytics"
    omni-kube-service-exposer.sidero.dev/prefix: "umami"
spec:
  selector:
    app: umami
  ports:
    - name: http
      port: 3000
      targetPort: 3000
