apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guacamole

resources:
  - network-policy.yaml
  - namespace.yaml
  - postgresql.yaml
  - guacd.yaml
  - guacamole.yaml
  - sealed-guacd-secret.yaml
  - sealed-oidc-secret.yaml
  - httproute.yaml
