apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-cloudflare-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCLaJh93Vj963925tQPpKTCPbn0eFmJXNPsadXyBGtYY3YS5D2lhgzmuUHCynmeffjThaN8KwUlhZFRHs1kLojXn65prs/8dzHq9vS87mjpyQxeUZvooWs6pgRcEDrWufWsUMxrJ8bRLfuhotdv4HP8EYl+oO57BaUyxPL31oEDD3iH5gejQrWqJrLHjTiOWtQFmf0+NNHK8JbP9hBWs63Y7VxDXrSKuR+oh1QytNxQhJUJjwGmjbgyYyiq13EQ6KN5STqWMWicZICU3HhrHd/PvJgnPNEzOeljpzmIS5l8P8ZeYmUcxh4S7iD9TbEtA2rRZVkv0z4KyvoxWdxhfKD7Mr7NXRLRHjOuNlMCow9ks4VbyEQbxhvZHtafvNd3aVtIag6mabHI34Ld8U2oEYN2rlwKhqVkNe0g4QuSBoMQycYyQ7k0EK8pSwSqI9WIJUVjXhM1+zsQmDzNEWqh6AAnr/dQJvJCoSbF3aeOPiVYGQinJ9PVfLEKWeGSXAR42EAUvrVbiTkuOOw81OOTjaPjtfggt4TQW/Px+r90FND2IdGQQtCIUUfpLzT+MAOt+FzYnMYdemIxXEr0B7bMyoIOk4X8SDpC8XNxrdiM1xpg3xVWN0JGHzmri+WoHnR2qUEBegUTbVtL5vwPfOwFTAKfZtpAUo9F2i3OMrpsIK5P88voCvySIxk5q0dF9W+cgd5/h2qwq9DDPD0aWXsPVyP/wUFg1yMuzrsJfQHI+8z+3h97ExVmcd8nm0Pk2HHWQ4aDpdUxVCgaHqlcGElWJfrdpzJQtMVNaN2zM9B+lDOyGIZ9GJfsVgIvWWlW7dAj773OQw+0mqUGOwJ4mVhGetksI1yWPnxvQ6IJ2FLEFqiDM1gbcweNmDblMu+xPeteTi+Az8ER
  template:
    metadata:
      name: velero-cloudflare-credentials
      namespace: velero
