apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-5.4.1
  name: default
  namespace: velero
spec:
  accessMode: ReadWrite
  config:
    region: auto
    s3ForcePathStyle: "true"
    s3Url: https://a51575eff9b7355d3dbdb591d77e6629.r2.cloudflarestorage.com
  objectStorage:
    bucket: homelab-velero-backups
  provider: aws
