---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-lapi-creds
  namespace: crowdsec
spec:
  encryptedData:
    csLapiSecret: AgBhfARnUu7bGvXGxI3jAAZ8p8QckkHvXcSaT3m9SAArOPiawrbIdnuauiq+M781uvnXzLACZ3ken54xmKLeNILdaNv8qhA+iF5WPEF/9NvFt2YC1Ib30dEbiAmseC2JFgfp7SWXg7BLYBYVN1A5gVmtbQ9/BepQlA0r7DmFSBeI6QiaNX0n2KJTSOZ4wwkuE1ZVFeSQZjdsNf+W50V+/C6/XoPRmpj5X1uKJd51ffkwvtUxmC3boiJSVIWWLBQBUn87TFXeVJsF4nL9saG8N7e5xrbBfUHui9hFI4KB9bxRoTGn+r9GzxB7qVWGwGNThMjOpg7d0gze/3n7k0fPsEkTzR/+r/VqINMzbtBOpNkhXq9E9mrIgfxdIjw0bP/AHnW4g2K0PNpZSlvAU8SdDrB/V3PAOmN/TBRChA8sI67GmSuuAaDwd9TegLLTqhGjXEZqcZ58t1ep4EI8F7MWWw63E3nmAbRB+z36UDkn70r0ehE2Bmmz2z2rKSvVpyT8qb0q3Q+esjE81qJrN3j2tqlQiUBXf0kiBqzj5tb/9AHxZ3By9D8wGblitCt6Y0N0THFpo667xdJWMQAmrVYvXzVqtG+QGPrfFwICBd6ZO3eQg/6ZT9d2zFU2DvkV2jMkLdkmNffaq2ey/iKCmtTk+nAu/ZfKICw5dp1xaXWPTaZS4MQvzTaL8wsoy9nscbp3mYPYqYkKKO5BeLqvVUJGaAD9QyNKm/xTB8wR+tcIaReT9q11XWe23wLwdqTWPNKBNxnjOYjdxmINuwbglQX8hZ6E
    registrationToken: AgA9DRGFI1HPlflnFceEIzYZ2Z4HzuBgEOWFqok63OjophXVnl1EwiGWOlS8JdxbwrxPLqpZ7RdJY2YkqBFBzCOlyazx08/OLhU1hla2mjhIQX66g4w1YPWPRx4g6qrmBAgPXtJ0529dXIcQMs8zCkolyTD8KVXHicdVNBRhTe4CgWANP12dBdSe4KhcJq9tl9pf/YfJRMgkvQueWJGftsPs2iPmC38Td3RiudKORwKXbKYYuhW3g7JgPcTX/lcsWH1Vgn3Ek6+emwt7ifNXz5rO5qoYAHJNFplgyUnaKe4x9poMFdOTrbKcKOgCPYgGHuISLg8RO7afj9qn+hS+apk5PIZyUsaDrhRYsgZZo1JR4lQWN5tP1whHf+xfiHNPGOpkoewhrKEp2TdC76ROHf7+VaLWne5yIuedQfMJ1LZv5vOls9XR+d0JQvDOvFcXlCGOscFVK2LlVChG+XvlPQAWBWMiPtdm3D3wiX+rPcwnSEFH0voz3wQJLCf2Gy5bi27nulKc8mdzZwddwgZxKWLVJfgwSkO1vPHQtBbKQZ8EvYt47+MwMVOdJxqxDZoCSo+g9R9AIcFaz9qE0J5h1idAtPndop/+quEybRthwzNMCpjtEY2rPChGB94SJmC8Lj/Hkg8weyXL4DuyFyME+qJh4JP57TprAn6bJ1ZSdon7DjwHrEmuo1X6qoV6Tlfw3JK32uPt2amVUlX2e64io62bWZjir5M+S1UimqrJMsxwxnD5K8BEkRZGNAINzQrYsAI=
  template:
    metadata:
      name: crowdsec-lapi-creds
      namespace: crowdsec
    type: Opaque
