apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: vaultwarden
name: vaultwarden
repo: https://guerzon.github.io/vaultwarden
chartHome: ../../../../../charts
releaseName: vaultwarden
namespace: vaultwarden
includeCRDs: false
skipHooks: false
version: 0.35.11
valuesFile: values.yaml
