apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC7NJwX1vNecOQjG3J58SaFIvMt2rjS0sM0LeBS+8IY/p7I66dSOA5W+X8EKpU6fXhUJDIR6iag2lniuKNvnjURaadaLnzXs5D8ek3ZFH0as9YHJl8gYyPnoRP6DrNA9iedM238cUQTkgDOJeHTY9F73VeSNp88zzC/YYJPzZ0js2VhGcZ/40Yd5fyAiieIKPVjt/5gCS3ZP5yoRU96xtDoNnK9v0RCxBLettbAaa9Dj8vpYBNR5/Hb5n1zDa7RyVQyGed0NXpk4I+NpZx+jMiNupHTedo4lHai6AX6mP/54iYuJPPAwV+NMJu3JMO4wHv3cd2WacW2gff8Qis8xhpB54qMk7qMdtP/YOMae7I4m1Eh29Gpx3YkTe6dTkG+UK1wPLV8Q9TYgbWJ4Xvnvt43/8HgRQADt8LfzXCg252zkTJ7AbREKiOb+EemV7kZJ4OE3jMI0svOoGZa5L25J4YyzYI3I5iaR01XSrlv0o+P2TXUzKn/SyrbLdSulDYi90jjxdFsJQFbPuVvwFnlBrfALwoBe9hrysv5u4YPddyq9RdR+pOMVPX4gNc+TDcONMcRB9Ww8dBshh0a5xnmZpRDKti95gAYy+pu7yhfmmpNU5G8nrJeouM8exmB+um3MVbwFu3Amh9AjKTYUwzO3CawfJCZKZRHKjA89upEOX3dDAXNCaKtYnLdZg80FurC7phUW5SZHZYBzx3lqLuYS/a1xP1ud8YveLP1E37PrnYS472NkLk6P4Fl+GMYGlmoH70vgpmgug==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
