apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulatorjs-config
  namespace: emulatorjs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulatorjs-data
  namespace: emulatorjs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 50Gi
