apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-postgres-data
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-minio-data
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 10Gi
