apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: znuny
  namespace: znuny
spec:
  parentRefs:
    - name: kgateway-http
      namespace: kgateway-system
  hostnames:
    - "tickets.srbii.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: znuny-app
          port: 80
