apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: znuny
resources:
  - ../../../../base/apps/znuny/
  - mariadb-statefulset.yaml
  - mariadb-service.yaml
  - znuny-deployment.yaml
  - znuny-service.yaml
  - httproute.yaml
  - sealed-znuny-db-secret.yaml
