apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znuny-data
  namespace: znuny
  labels:
    app: znuny-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 15Gi
