apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/apps/sealed-secrets/

patches:
  - target:
      kind: HelmChartInflationGenerator
      name: sealed-secrets
    patch: |-
      - op: replace
        path: /valuesFile
        # Point back to the helm directory from the kustomize build directory
        value: ../../../../../helm/overlays/scots-lab/apps/sealed-secrets/values-scots-lab.yaml
