global:
  env: scots-lab
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL: https://github.com/ghubprime/k8s-cluster.git
      targetRevision: HEAD

argocdApplications:
  argocd:
    disableAutomated: false
    disable: false
    name: argocd
    namespace: argocd
    appCategory: apps
    syncWave: "1"
  talos:
    disableAutomated: false
    disable: false
    name: talos
    namespace: talos-system
    appCategory: cluster
    syncWave: "1"
  omni:
    repoURL: https://github.com/ghubprime/omni-infra.git
    path: "."
    disableAutomated: false
    disable: false
    name: omni
    namespace: omni-system
    directory:
      recurse: true
      include: "{manifests/*}"
    appCategory: cluster
    syncWave: "1"
  hostNetwork:
    disableAutomated: false
    disable: true
    name: host-network
    namespace: kube-system
    appCategory: infra
    syncWave: "0"
  multus:
    disableAutomated: false
    disable: false
    name: multus
    namespace: kube-system
    appCategory: infra
    syncWave: "0"
  whereabouts:
    disableAutomated: false
    disable: false
    name: whereabouts
    namespace: kube-system
    appCategory: infra
    syncWave: "0"
  cilium:
    disableAutomated: false
    disable: false
    name: cilium
    namespace: kube-system
    appCategory: infra
    syncWave: "0"
  gateway-api-crds:
    disableAutomated: false
    disable: false
    name: gateway-api-crds
    appCategory: cluster
    syncWave: "-1"
  kube-prometheus-stack:
    disableAutomated: false
    disable: false
    name: kube-prometheus-stack
    namespace: kube-prometheus-system
    appCategory: monitoring
    syncWave: "3"
  rook-ceph:
    disableAutomated: false
    disable: false
    name: rook-ceph
    namespace: rook-ceph
    appCategory: apps
    syncWave: "1"
  rook-ceph-cluster:
    disableAutomated: false
    disable: false
    name: rook-ceph-cluster
    namespace: rook-ceph
    appCategory: cluster
    syncWave: "2"
    ignoreDifferences:
      - group: ceph.rook.io
        kind: CephCluster
        jsonPointers:
          - /spec/storage/metadataDevice
  argocdApps:
    disableAutomated: false
    disable: false
    name: argocd-apps
    namespace: argocd
    appCategory: apps
    ignoreDifferences:
      - group: argoproj.io
        kind: Application
        jsonPointers:
          - /spec/syncPolicy
  certManager:
    disableAutomated: false
    disable: false
    name: cert-manager
    namespace: cert-manager
    appCategory: apps
    syncWave: "1"
  kgateway-crds:
    disableAutomated: false
    disable: false
    name: kgateway-crds
    appCategory: cluster
    syncWave: "-1"
  kgateway:
    disableAutomated: false
    disable: false
    name: kgateway
    appCategory: cluster
    syncWave: "2"
  sealedSecrets:
    disableAutomated: false
    disable: false
    name: sealed-secrets
    namespace: kube-system
    appCategory: apps
    syncWave: "1"
  velero:
    disableAutomated: false
    disable: false
    name: velero
    namespace: velero
    appCategory: apps
    syncWave: "1"
  crowdsec:
    disableAutomated: false
    disable: false
    name: crowdsec
    namespace: crowdsec
    appCategory: security
    syncWave: "1"
  loki:
    disableAutomated: false
    disable: false
    name: loki
    namespace: loki
    appCategory: monitoring
    syncWave: "3"
  uptime-kuma:
    disableAutomated: false
    disable: false
    name: uptime-kuma
    namespace: uptime-kuma
    appCategory: apps
    syncWave: "3"
  nextcloud:
    disableAutomated: false
    disable: false
    name: nextcloud
    namespace: nextcloud
    appCategory: apps
    syncWave: "3"