apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ceph-objectstore
  namespace: rook-ceph
spec:
  dataPool:
    deviceClass: ssd
    failureDomain: host
    parameters:
      bulk: "true"
    replicated:
      size: 3
  gateway:
    instances: 1
    opsLogSidecar:
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: null
          memory: 40Mi
    port: 80
    priorityClassName: system-node-critical
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: null
        memory: 1Gi
  metadataPool:
    deviceClass: ssd
    failureDomain: host
    replicated:
      size: 3
  preservePoolsOnDelete: true
