apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: crowdsec-extauth-extension
  namespace: kgateway-system
spec:
  extAuth:
    grpcService:
      backendRef:
        group: ""
        kind: Service
        name: crowdsec-envoy-bouncer
        namespace: crowdsec
        port: 8080
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: crowdsec-extauth-policy
  namespace: kgateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: kgateway
  policy:
    extAuth:
      extensionRef:
        name: crowdsec-extauth-extension
        namespace: kgateway-system
