env:
  TZ: "UTC"
  PAPERLESS_URL: "https://docs.srbii.com"
  PAPERLESS_ENABLE_ALLAUTH: "true"
  PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
  PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
  PAPERLESS_DISABLE_REGULAR_LOGIN: "false"

envValueFrom:
  PAPERLESS_SOCIALACCOUNT_PROVIDERS:
    secretKeyRef:
      name: paperless-oidc-secret
      key: providers.json

ingress:
  main:
    enabled: false

persistence:
  data:
    enabled: true
    storageClass: "ceph-block"
    accessMode: ReadWriteOnce
    size: 2Gi
    retain: true
  media:
    enabled: true
    storageClass: "ceph-block"
    accessMode: ReadWriteOnce
    size: 15Gi
    retain: true
  export:
    enabled: true
    storageClass: "ceph-block"
    accessMode: ReadWriteOnce
    size: 5Gi
    retain: true
  consume:
    enabled: true
    storageClass: "ceph-block"
    accessMode: ReadWriteOnce
    size: 4Gi
    retain: true

postgresql:
  enabled: true
  image:
    tag: "16"
  auth:
    database: paperless
    postgresPassword: changeme
  primary:
    persistence:
      enabled: true
      storageClass: "ceph-block"
      size: 10Gi

redis:
  enabled: true
  image:
    tag: "7.4"
  auth:
    enabled: true
    password: changeme
  master:
    persistence:
      enabled: true
      storageClass: "ceph-block"
      size: 5Gi
  replica:
    replicaCount: 0
