apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scots-lab-wildcard-tls
  namespace: kgateway-system
spec:
  secretName: scots-lab-wildcard-tls
  issuerRef:
    name: scots-lab-ca-issuer
    kind: ClusterIssuer
  commonName: "*.scots-lab.local"
  dnsNames:
  - "*.scots-lab.local"
  - "scots-lab.local"
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
# CI trigger
metadata:
  name: kgateway-http
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      namespaces:
        from: All
  - protocol: HTTPS
    port: 443
    name: https
    hostname: "*.scots-lab.local"
    tls:
      mode: Terminate
      certificateRefs:
      - name: scots-lab-wildcard-tls
    allowedRoutes:
      namespaces:
        from: All