apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kgateway-pdb
  namespace: kgateway-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kgateway
