apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cluster/kgateway/
  - kgateway-http.yaml
  - extauth-policy.yaml
generators:
  - ../../../../../helm/overlays/scots-lab/cluster/kgateway/