---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgA/ENR2PoTuYukKTYIEcuCY27EDWahKIlgG9bMKZxww4EnG+3r1DpF9CfHcPU7MHqawSMiUHn4lP5mnV3IKs1WPM1OAET3DQuFheitVLxmw9i8KnwdFnZMy+7pE0AinmfVreJ6hTPF/t48F03FhKg8lyXnRZDhCGpCWWqiQxVvWRlsqlL+5O+3RtkIJFJ1RmN1iXRIap+p2s/i6vAjR8aiLnb5nOAWexpf/RTPBtDdXZWsRysE7DOKk94HBc6/Q87slav3UR7KDcs0RW+EJNFy/QJeGYZifKEPEYgmdqEfkhw6igP+fNvDZrFPhFdQjAHTogzVR8uPiOvmCZornyLdUAB8I0zVeT5vBVvTOX7Ig83FA5BS9wrQCLPOnW8kZkpHt0hFl7luiGuiM1tE66i/iHVeBKeohb7mnByFWXE3wdLarRX3xLU0Fr2+H89QKeMHARZ/WoiflZyil5UYQlXO1lrLjFI0IeIWX+csXGBHsNuXPiP63xxY+G17VVZLT7sc60jZjvJkBNZYtOTzuYfzFTWb6KqNXdKL+EP1RG6Cp6gVzefO8sJHknVwT2pzMfmn7dq9OplYx3fbR/xNa/MpG2micXVipM2MYVqu3AAKhTbw9nRJIf7cE8eTNtZtNNBFde0xvL4H6JHCPbCD1HkT+LZqbIy/glRzs4ZDfRmv90hC85wJ7QqEAqCGubcHqnl1erefMku2JoYD2KYlbQkqq4s0eSbXKk1yjeLVZfrIlJw==
  template:
    metadata:
      name: keycloak-admin-credentials
      namespace: keycloak
