apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: healthchecks
resources:
  - ../../../../base/apps/healthchecks/
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - httproute.yaml
  - sealed-oauth2-proxy-secret.yaml
