apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../../../base/apps/sealed-secrets/
helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.18.6
    releaseName: sealed-secrets
    namespace: kube-system
    includeCRDs: true
    valuesFile: ../../../../../helm/overlays/scots-lab/apps/sealed-secrets/values-scots-lab.yaml
