apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../../../base/infra/metrics-server/
helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    releaseName: metrics-server
    namespace: kube-system
    version: 3.14.0
    includeCRDs: true
    valuesFile: ../../../../../helm/overlays/scots-lab/infra/metrics-server/values-scots-lab.yaml
