apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 5.4.1
    releaseName: velero
    namespace: velero
    includeCRDs: true
    valuesFile: ../../../../../helm/overlays/scots-lab/apps/velero/values-scots-lab.yaml
