controllers:
  main:
    containers:
      main:
        image:
          tag: v1.132.3
        env:
          DB_HOSTNAME: "immich-postgres"
          DB_USERNAME: "immich"
          DB_PASSWORD: "immich"
          DB_DATABASE_NAME: "immich"
          REDIS_HOSTNAME: "immich-redis-master"
          DB_URL: "postgresql://immich:immich@immich-postgres:5432/immich?sslmode=disable"

server:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

machine-learning:
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2Gi

immich:
  persistence:
    library:
      existingClaim: immich-library-pvc
