---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: onetimesecret-secret
  namespace: onetimesecret
spec:
  encryptedData:
    SECRET: AgA37D9VGRIVbl4lq73beJkwyx783rMQ/6/7HIzECFYBeCVwGEshGXDsZQKKkGewhBIcVXnIqeh1X/furpgdF4Y7qokQ7xr8tgtIBkSdQeSxTX+w9fDbiPZVRrYURzez3fRgKp64lC68ZhRtztCL7v+eGMnhgB1Q2G1moxPlOV90YquHyFC0E6gVmRASHza1dEOl1A7aJPDFt8CHMF+7Or8GstZuPpfWJcayjrfGNt2rEaUN67eo2nRbjmHNtMOOA31EtrZRsn2z6nfQSI7Flx6RXWkLK0AkkGfPlQFgjMeiQXZmy08J5H/t+NuZfIGjkxyOvlAABOCzAkef1lx+FU52v5whUWbgas0w98uo+FEdz+s3TaPxSAba2zPHhlrdqT3FVpQJhq32IHWcd7VjTGY04Et5ssRYiETvSrhTZIFeO1zzqRmbCsL8Jm+gUhptaEvDV0XmEoU/xo1tDZ/8o9fZWQPeqfUAf6l4VabwTs2rAx2nzb/eRPgzSq17EQEL5gEmGMtBOxjWG7BxZC/lzz9KQI5WhCislRwZKBLxE8HfS0OCRiaENl6PC7tY8YJksIJObdOwAphiir4Oq8YlQosLxsMRGxG7LCxfrip3yJPzRu2jov0lZFElENKC+LMfzPJXPt3qU8onouRTX4Kd+BWX7pNRo9UJv9M/Q0xKsea3GlqLA08wPk6ZLWFRg5QZWUjS1VLzEWHaSJjWJm0zQWJCPLYQHZ//Qg41NHINU0Y3d3kI079d55RbOqKCST33z3BrE6ZrztE3ZJ+WRZiY7gOS
  template:
    metadata:
      name: onetimesecret-secret
      namespace: onetimesecret
