# Keycloak values for scots-lab environment

auth:
  adminUser: admin
  existingSecret: keycloak-admin-credentials
  passwordSecretKey: admin-password

production: false

postgresql:
  enabled: true
  primary:
    persistence:
      storageClass: "ceph-block"

ingress:
  enabled: true
  ingressClassName: "cilium"
  hostname: keycloak.proxy-us.srbii.com
  tls: false
