apiVersion: v1
data:
  cron-expression: 30 4 * * *
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: |
      Configmap containing user customizable cronjob schedule
  name: whereabouts-config
  namespace: kube-system
