apiVersion: builtin
kind: HelmChartInflationGenerator
name: kube-prometheus-stack
metadata:
  name: kube-prometheus-stack
chartHome: ../../../../../charts/kube-prometheus-stack-72.6.3
releaseName: kube-prometheus-stack
#namespace: prometheus
includeCRDs: true
skipHooks: false
version: 72.6.3