apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-prometheus-system
resources:
  - ../../../../base/monitoring/kube-prometheus-stack/
  - sealed-grafana-oidc-secret.yaml
helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 72.6.3
  releaseName: kube-prometheus-stack
  namespace: kube-prometheus-system
  includeCRDs: true
  valuesFile: ../../../../../helm/overlays/scots-lab/monitoring/kube-prometheus-stack/values-scots-lab.yaml
patches:
  - patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: Replace=true
    target:
      kind: CustomResourceDefinition