---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: kube-prometheus-system
spec:
  encryptedData:
    admin-password: AgBZHSLaI0b/iUf5dXT9lYLbcm64vSk78ZuZO8hLOdjYlCVzFFc2vE+6CbK5kLF1Bpb8LzIlyorFoYQ9V38wENyocx40eNZuVLaQXR5ixqqBUhOVS7M3t6rftc6nFi5nQsvjS0DnkCaBgyeeOhcKYsVXoD69o5MkHNqVNydvEe1iHLzROajpnPkdVXjFW7FvN2vR4tgY4r8suQOj8BYhmkth0IPtr9mVnDqXk5oQDntFwcJEBEHVCdyJcNrp0atO+/ZGXBGhiPqhzNpaWbMdIXSrAW7qLO6AyA+dq4zZt6vFtkybSX+2jl7x2xfc5WL/IW+AMRLRsU2rAMeGRsNd0Ew7/WGO7y3hp4JKPrHbY1henlMNu9d17VGtYZnv+geshMo+djjX4MfatXJLiLpK8XTK94z26uJVAUj2JxS1vtcPV1fKOe5CaAcMfSichVpEe36ByHmtiOgDcUFR/H86LOQueBjyh8ALfgbnkEb979UJlQGcdCCY1j0Kp1vHAVBoDPzLu9Tlsz4DBKJ67JU0I7zzQkftu8HJWz78RiN+CjivA3Q3HQHtx4Qi4M9N8kiZbN2DPf7mKeVxPOjG82f+Cq68kIbja1UElRwLnn1z0YLBqRZM/aG0H45bo8lVRD7SgURRwaPNmq1W5UD94Bpr8n3df0tPZuPk8yNHi+uuhqMXwup8ZQ/LevPlzdg1hI1ga01bEj8cwrTO412vv8yVn54veDzkwmz5ly6cG5wAaGdF0ovM2kqk3EXr
    admin-user: AgCkTJe+GrZJhGWeuOayV9a5PcMnAIPYsdCpLEWmg2XAkWDC21rd1/PBXA6Vt3nnMw6hJtHp2fvfkHscAJDM3W4qakcwdGHjXi+QZhx7oLgNeI0zszvObNRQwqCwPF2ohunOLHr5SDIHyA2pklXE8y4U9+WuH6JrhiO69jrBsWcLKcV/vZQdxoALofXZf/Kr7Xqad1V3qMNSgSRTnRwemnKnqbWVH61wr1VIlB6v4iy/PR0jSrB7xjHkGgheta0Qwr/WiZTP/E53prNpfaOoaxhagw/xI1JD5LZqNdIGgI08dXeFqH0DXKCp9J8hdgrzAZ1Cgw8uzMHaIRBw9XaoP+yb2KWaqWizzcnEHMScZx9eNIUJ3Y9WXENZ0HzmsHaUfmckMXUiCTGy5F5Gxrn0bhZlYS56lq1RpaZmzJMAngXaJlYNreF701GEGnVQJvU8eFXIxyxAgPbM8vDv8cou6RFi6gtJu13rNVp8uVcTRCoHUpWzFvO84WkYbmR7qlkGj7V+35ZDbgt9XHSaiJo5esiqZGsdW9YmrN3OnWvw530k6V5xjSnztb7fxNoc1/E+diR0c33dOQAsuiYNJxSRXDXW/pwwXzRMR+Xhv0rZmN6no6YPyrn8XeKV17t8VQN5N5Zqn2XQEiutmkXnUaa4ZT9hjbXNIv2ttwlcArTU72xYeOPknoMbTgGAGIcyNCCJ6IrWIlFFNg==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: kube-prometheus-system
    type: Opaque
