container_runtime: containerd

agent:
  env:
    - name: PARSERS
      value: "crowdsecurity/envoy-logs"
  acquisition:
    - namespace: kgateway-system
      podName: kgateway-*
      program: kgateway

lapi:
  env:
    - name: BOUNCER_KEY_KUBERNETES
      value: "kubernetes-bouncer-static-key"

