apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/apps/argocd/
  - sealed-oidc-secret.yaml
  - argocd-pdb.yaml
  - emergency-unban.yaml
  - httproute.yaml
namespace: argocd
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.0.5
    releaseName: argo-cd
    namespace: argocd
    includeCRDs: true
    valuesFile: values-scots-lab.yaml
patches:
  - path: dashboard-patch.yaml
