---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgBF9u8ikSiEPvCKMP+pr11QC+hJyoTvhHQdNGMHhSVOx1biV96hVtzIjaT3ZMOZYtUyfDYZJzVafLZRBwEW7o6+nm/kUGWA43Jjb6EJGYUw3HBoVbTgS0QqwLvlD+hjyGQ7iYzYohydjeK0TIsVcGJzqT8p+63KJmnm2tF1HvqvooJD0Q0NXk4cJH6/9ojuAAytFACuuKrt4m/2JQdDEMfGWYpHkUCiggm/p36v6rv3747qctbHWMwHtxjxiJVU06bMp0/lIHEtUtua4UGVXpSW7QKbkFCGMQ09M6FWxYhWqmJI0rLTl6MtyqOLBcx9RtyWFcCO9navAlTIm7tPtVXuGWZFbHb93bTEVxORph0DAJm8mxhCT/bZzbIP1Vh0eM0AVdIpMFmK/KgQUlQm7vR2JC8UzFtZTcYeIr5j1wjVIbvmC7LLNWO/B1P6xbdsLcjUNohrabKLr6v5lGPpFmnWAPWCmjQ8hi59Oefrjcw8cwjthyUkk30xOus2vKKsrLjYu5w9hKMB9eGC6XD29lzxhCoq3Cj0DT1MHDmQHtCFjSuZys4hBECEuBHzYwOV9E3/fLlqICZZbGy+ACIgUssCdQuybF/u8ipU57uMepiPygSLlqlOEsbVjQApB5Gre8pae+3pKfmDAHY32+TVieOslzN2fme1rSZlkpCAYJD1RE6SXh+bSpDEB8nf8hN2Umn9ebC2lgoJcVushI44ezdu4AlCn4/nSt3pPX0/a44b9g==
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
